import {shadePhotosFor} from './shade-photos';
import {M, type LocalText, type Locale, type Word} from './i18n';
export type Category='wigs'|'ponytails'|'clip-ins'|'hairpieces'|'natural-hair'|'hair-care';
export type Variant={id:string;label:LocalText;price:number;length?:number;grams?:number};
export type Product={id:string;sourceId:number;slug:string;name:LocalText;category:Category;description:LocalText;images:string[];shades:string[];textures:('straight'|'wavy')[];variants:Variant[];material:'human'|'slavic'|'european'|'care';soldOut?:boolean;unit?:'capsule'|'100g';careType?:string;brand:string;};
export const imagePath=(id:number,seq=1)=>`/images/cat-${id}-${String(seq).padStart(2,'0')}.webp`;
export const shades:Record<string,{name:LocalText;hex:string;group:'blonde'|'brunette'|'ombre'}>={
 '613':{name:M('Natural blonde','Biondo naturale','Dabiski blonds','Натуральный блонд'),hex:'#e8d3a4',group:'blonde'},
 '1/613':{name:M('Dark-to-blonde ombré','Ombré scuro-biondo','Tumšs–blonds ombré','Омбре тёмный–блонд'),hex:'linear-gradient(135deg,#30241f 45%,#dfc68e 55%)',group:'ombre'},
 '10.7':{name:M('Beige blonde','Biondo beige','Bēši blonds','Бежевый блонд'),hex:'#c9b18a',group:'blonde'},'10.0':{name:M('Natural blonde','Biondo naturale','Dabiski blonds','Натуральный блонд'),hex:'#dcc8a2',group:'blonde'},'9.3':{name:M('Wheat blonde','Biondo grano','Kviešu blonds','Пшеничный блонд'),hex:'#c2a16d',group:'blonde'},'9.0':{name:M('Golden blonde','Biondo dorato','Zeltaini blonds','Золотистый блонд'),hex:'#c5a56e',group:'blonde'},
 '7.1/10.1':{name:M('Ash blonde ombré','Ombré biondo cenere','Pelnu blonds ombré','Пепельный омбре'),hex:'linear-gradient(135deg,#887360 45%,#dac8b1 55%)',group:'ombre'},'6.0/10.0':{name:M('Golden blonde ombré','Ombré biondo dorato','Zeltaini blonds ombré','Золотистый омбре'),hex:'linear-gradient(135deg,#725442 45%,#d7bd86 55%)',group:'ombre'},'8.74':{name:M('Light copper brown','Castano chiaro ramato','Gaiši brūns vara tonis','Светло-русый медный'),hex:'#b18356',group:'brunette'},'8.71':{name:M('Light ash brown','Castano chiaro cenere','Gaiši pelnu brūns','Светло-русый пепельный'),hex:'#ae9b82',group:'brunette'},'8.3':{name:M('Golden light brown','Castano chiaro dorato','Zeltaini gaiši brūns','Светло-русый золотистый'),hex:'#b89a69',group:'brunette'},'8.0':{name:M('Light brown','Castano chiaro','Gaiši brūns','Светло-русый'),hex:'#ae926e',group:'brunette'},'7.71':{name:M('Ash brown','Castano cenere','Pelnu brūns','Русый пепельный'),hex:'#8e7a62',group:'brunette'},'7.1':{name:M('Medium ash brown','Castano medio cenere','Vidēji pelnu brūns','Средне-русый пепельный'),hex:'#82705d',group:'brunette'},'7.0':{name:M('Medium golden brown','Castano medio dorato','Vidēji zeltaini brūns','Средне-русый золотистый'),hex:'#97704b',group:'brunette'},'6.74':{name:M('Warm chocolate','Cioccolato caldo','Silts šokolādes tonis','Тёплый шоколад'),hex:'#74503b',group:'brunette'},'6.71':{name:M('Dark ash brown','Castano scuro cenere','Tumši pelnu brūns','Тёмно-русый пепельный'),hex:'#645447',group:'brunette'},'6.7':{name:M('Deep brown','Castano intenso','Dziļi brūns','Тёмно-русый коричневый'),hex:'#78553a',group:'brunette'},'6.0':{name:M('Dark golden brown','Castano scuro dorato','Tumši zeltaini brūns','Тёмно-русый золотистый'),hex:'#7a583a',group:'brunette'},'5.71':{name:M('Cool chocolate','Cioccolato freddo','Vēss šokolādes tonis','Холодный шоколад'),hex:'#514238',group:'brunette'},'5.7':{name:M('Warm deep brown','Castano scuro caldo','Silts tumši brūns','Тёплый тёмный шатен'),hex:'#65412e',group:'brunette'},'3.0':{name:M('Dark brunette','Castano scuro','Tumšs kastanis','Тёмный шатен'),hex:'#38271f',group:'brunette'},'1.1':{name:M('Blue black','Nero blu','Zilgani melns','Сине-чёрный'),hex:'#1f2228',group:'brunette'},'1.0':{name:M('Black','Nero','Melns','Чёрный'),hex:'#211c1c',group:'brunette'},'6.7/9.7':{name:M('Brown-to-blonde ombré','Ombré castano-biondo','Brūns–blonds ombré','Омбре коричневый–блонд'),hex:'linear-gradient(135deg,#694830 45%,#c3a17b 55%)',group:'ombre'},'10.16':{name:M('Platinum blonde','Biondo platino','Platīna blonds','Платиновый блонд'),hex:'#ded6c6',group:'blonde'},'6.0/10.7':{name:M('Beige ombré','Ombré beige','Bēšs ombré','Бежевый омбре'),hex:'linear-gradient(135deg,#75583d 45%,#c9b18a 55%)',group:'ombre'},'6.74/9.7':{name:M('Warm ombré','Ombré caldo','Silts ombré','Тёплый омбре'),hex:'linear-gradient(135deg,#744b30 45%,#c4a16c 55%)',group:'ombre'},
 '1':{name:M('Black','Nero','Melns','Чёрный'),hex:'#211d1b',group:'brunette'},'1B':{name:M('Blue black','Nero blu','Zilgani melns','Сине-чёрный'),hex:'#25252b',group:'brunette'},'6':{name:M('Light brown','Castano chiaro','Gaiši brūns','Светло-коричневый'),hex:'#8e674d',group:'brunette'},'10':{name:M('Light brown','Castano chiaro','Gaiši brūns','Светло-русый'),hex:'#b18f68',group:'brunette'},'12':{name:M('Ash light brown','Castano chiaro cenere','Gaiši pelnu brūns','Пепельно-русый'),hex:'#a89880',group:'brunette'}
};
const hairShades=['10.7','10.0','9.3','9.0','7.1/10.1','6.0/10.0','8.74','8.71','8.3','8.0','7.71','7.1','7.0','6.74','6.71','6.7','6.0','5.71','5.7','3.0','1.1','1.0'];
const variant=(id:string,label:string,price:number,length?:number,grams?:number):Variant=>({id,label:M(label,label,label,label),price,length,grams});
const wigDescription=M('Handcrafted natural-hair wigs with a breathable mesh base and an adjustable fit. Designed to be cut and styled to suit you. Speak to our team before colouring or making permanent changes.','Parrucche in capelli naturali lavorate a mano, con base in rete traspirante e vestibilità regolabile. Si possono tagliare e acconciare per valorizzarti. Contattaci prima di colorazioni o modifiche permanenti.','Ar rokām darinātas dabīgo matu parūkas ar elpojošu tīkliņa pamatni un regulējamu izmēru. Tās var pielāgot ar griezumu un veidošanu. Pirms krāsošanas vai neatgriezeniskām izmaiņām sazinies ar mums.','Парики ручной работы из натуральных волос, с дышащей сетчатой основой и регулируемой посадкой. Стрижка и укладка помогут адаптировать образ. Перед окрашиванием или необратимыми изменениями свяжитесь с нами.');
const clipDescription=M('Handcrafted from natural Slavic hair. Add length and fullness with removable clips, and wear the pieces together or individually. Custom lengths, shades and density can also be discussed.','Realizzate a mano con capelli slavi naturali. Aggiungi lunghezza e volume con clip rimovibili, indossando le ciocche insieme o singolarmente. Possiamo valutare anche lunghezze, tonalità e densità su misura.','Ar rokām darināti no dabīgiem slāvu matiem. Noņemamās sprādzes ļauj piešķirt garumu un apjomu, lietojot šķipsnas kopā vai atsevišķi. Var vienoties arī par individuālu garumu, toni un biezumu.','Изготовлены вручную из натуральных славянских волос. Съёмные заколки добавляют длину и объём; пряди можно сочетать или носить отдельно. Индивидуальные длину, оттенок и густоту можно обсудить с командой.');
const cutDescription=M('Selected loose cut hair for professional preparation. Your stylist can choose strand weight and prepare it for hot or cold extension methods, or create a weft. Published prices are per 100 g.','Capelli selezionati in taglio per la preparazione professionale. Lo stylist può scegliere il peso delle ciocche e prepararle per applicazioni a caldo, a freddo o in tessitura. Prezzi per 100 g.','Atlasīti mati griezumā profesionālai sagatavošanai. Meistars var izvēlēties šķipsnu svaru un sagatavot tās karstajai, aukstajai pieaudzēšanai vai treses izgatavošanai. Cena par 100 g.','Отобранные волосы на срезе для профессиональной подготовки. Мастер выбирает толщину прядей и готовит их для горячего или холодного наращивания либо изготовления тресса. Цена указана за 100 г.');
export const products:Product[]=[
{id:'wig-blonde',sourceId:1848,slug:'natural-blonde-wig',name:M('Natural blonde wig','Parrucca biondo naturale','Dabiski blonda parūka','Парик натуральный блонд'),category:'wigs',description:wigDescription,images:[imagePath(1848,2),imagePath(1848,1)],shades:['613'],textures:[],variants:[variant('48','48 cm · 250 g',525,48,250),variant('57','57 cm · 250 g',570.5,57,250)],material:'human',brand:'BM HAIR'},
{id:'wig-dark',sourceId:1847,slug:'dark-natural-hair-wig',name:M('Dark natural-hair wig','Parrucca castana naturale','Tumša dabīgo matu parūka','Парик тёмных оттенков'),category:'wigs',description:wigDescription,images:[imagePath(1847,2),imagePath(1847,3),imagePath(1847,4),imagePath(1847,6)],shades:[],textures:[],variants:[{id:'one',label:M('One size · style confirmed with our team','Taglia unica · stile da confermare','Viens izmērs · stils jāprecizē','Один размер · модель уточняется'),price:199}],material:'human',brand:'BM HAIR'},
{id:'wig-highlight',sourceId:1848,slug:'highlighted-natural-hair-wig',name:M('Highlighted natural-hair wig','Parrucca naturale con mèches','Dabīgo matu parūka ar šķipsnām','Парик с мелированием'),category:'wigs',description:wigDescription,images:[imagePath(1848,3),imagePath(1848,4)],shades:[],textures:[],variants:[{id:'one',label:M('Natural brown / highlights','Castano naturale / mèches','Dabiski brūns / gaišas šķipsnas','Натуральный русый / мелирование'),price:199}],material:'human',brand:'BM HAIR'},
{id:'ponytail',sourceId:1820,slug:'slavic-hair-ponytail',name:M('The natural ponytail','La coda naturale','Dabīgo matu zirgaste','Натуральный хвост'),category:'ponytails',description:M('A fuller ponytail, a sleek finish or a braid: one piece, many possibilities. Each ponytail is handcrafted from natural Slavic hair. Choose your length and shade, or ask about a custom piece.','Una coda piena, un look liscio o una treccia: un solo accessorio, tante possibilità. Ogni coda è realizzata a mano con capelli slavi naturali. Scegli lunghezza e tonalità, o richiedila su misura.','Kupla zirgaste, gluds tēls vai bize: viens aksesuārs, daudz iespēju. Katra zirgaste darināta ar rokām no dabīgiem slāvu matiem. Izvēlies garumu un toni vai jautā par individuālu pasūtījumu.','Объёмный хвост, гладкая укладка или коса: одно изделие — много вариантов. Каждый хвост изготовлен вручную из натуральных славянских волос. Выберите длину и оттенок или обсудите индивидуальный заказ.'),images:[imagePath(1820,2),imagePath(1820,3),imagePath(1820,1)],shades:['613','1/613'],textures:['straight','wavy'],variants:[variant('50','50–55 cm',319,50),variant('55','55–60 cm',339,55),variant('60','60–65 cm',359,60),variant('70','70–75 cm',379,70)],material:'slavic',brand:'BM HAIR'},
{id:'clip-ins',sourceId:1821,slug:'slavic-hair-clip-ins',name:M('Natural hair clip-ins','Extension naturali a clip','Dabīgie mati ar sprādzēm','Натуральные волосы на заколках'),category:'clip-ins',description:clipDescription,images:[imagePath(1821,2),imagePath(1821,3),imagePath(1821,4),imagePath(1821,5),imagePath(1821,6)],shades:['613','6.74','6.7/9.7','10.16','1.0'],textures:[],variants:[variant('45','45–50 cm · 100 g',389,45,100),variant('50','50–60 cm · 100 g',429,50,100),variant('60','60–70 cm · 100 g',469,60,100)],material:'slavic',brand:'BM HAIR'},
{id:'mono',sourceId:1960,slug:'mono-clip-in',name:M('Mono clip-in','Mono clip-in','Mono clip-in','Моно-заколка'),category:'clip-ins',description:clipDescription,images:[imagePath(1960,2),imagePath(1960,3),imagePath(1960,4)],shades:['6.0/10.7','5.71','6.74/9.7'],textures:[],variants:[variant('45','45–50 cm · 100 g',389,45,100),variant('50','50–60 cm · 100 g',429,50,100),variant('60','60–70 cm · 100 g',469,60,100)],material:'slavic',brand:'BM HAIR'},
{id:'slavic-cut',sourceId:1822,slug:'slavic-cut-hair',name:M('Slavic cut hair','Capelli slavi in taglio','Slāvu mati griezumā','Славянские волосы на срезе'),category:'natural-hair',description:cutDescription,images:[imagePath(1822,2),imagePath(1822,3),imagePath(1822,4)],shades:hairShades.filter(s=>s!=='10.0'),textures:['straight','wavy'],variants:[variant('40','40 cm · 100 g',287,40,100),variant('50','50 cm · 100 g',305,50,100),variant('60','60 cm · 100 g',324,60,100),variant('70','70 cm · 100 g',335,70,100)],material:'slavic',unit:'100g',brand:'BM HAIR'},
{id:'european-cut',sourceId:1846,slug:'european-cut-hair',name:M('European cut hair','Capelli europei in taglio','Eiropas mati griezumā','Европейские волосы на срезе'),category:'natural-hair',description:cutDescription,images:[imagePath(1846,2),imagePath(1846,3),imagePath(1846,4)],shades:['1','1B','6','10','12'],textures:['straight','wavy'],variants:[variant('50','50 cm · 100 g',148,50,100),variant('60','60 cm · 100 g',148,60,100)],material:'european',unit:'100g',brand:'BM HAIR'},
{id:'capsules',sourceId:1810,slug:'slavic-capsule-extensions',name:M('Slavic capsule extensions','Extension slave con cheratina','Slāvu mati uz kapsulām','Славянские волосы на капсулах'),category:'natural-hair',description:M('Natural Slavic hair prepared in individual capsules for professional application. Select length, texture and shade. The price is for one capsule; your stylist should confirm the quantity for your own hair.','Capelli slavi naturali in ciocche con cheratina, per applicazione professionale. Scegli lunghezza, texture e tonalità. Prezzo per una ciocca: il tuo stylist confermerà la quantità adatta.','Dabīgie slāvu mati atsevišķās kapsulās profesionālai pieaudzēšanai. Izvēlies garumu, struktūru un toni. Cena par vienu kapsulu; piemēroto daudzumu nosaka meistars.','Натуральные славянские волосы на отдельных капсулах для профессионального наращивания. Выберите длину, структуру и оттенок. Цена за одну капсулу; нужное количество определит мастер.'),images:[imagePath(1810,2),imagePath(1810,3),imagePath(1810,4)],shades:hairShades,textures:['straight','wavy'],variants:[variant('40','40 cm',2.25,40),variant('50','50 cm',2.4,50),variant('60','60 cm',2.6,60),variant('70','70 cm',2.9,70)],material:'slavic',unit:'capsule',brand:'BM HAIR'},
];
const careRows:[number,string,LocalText,number,boolean,LocalText][]=[
[1823,'couture-luxury-blond-spray',M('Couture Luxury Blond · two-phase spray','Couture Luxury Blond · spray bifasico','Couture Luxury Blond · divfāžu sprejs','Couture Luxury Blond · двухфазный спрей'),20.4,true,M('A two-phase detangling spray with argan oil, pearl extract, silk proteins and keratin.','Spray bifasico districante con olio di argan, estratto di perla, proteine della seta e cheratina.','Divfāžu sprejs vieglākai ķemmēšanai ar argāna eļļu, pērļu ekstraktu, zīda proteīniem un keratīnu.','Двухфазный спрей для лёгкого расчёсывания с маслом арганы, экстрактом жемчуга, протеинами шёлка и кератином.')],
[1825,'otium-diamond-oil',M('Otium Diamond · precious oil','Otium Diamond · olio prezioso','Otium Diamond · matu eļļa','Otium Diamond · драгоценное масло'),19,true,M('A finishing oil for smoothness and shine, with camellia and argan oils.','Olio per morbidezza e lucentezza, con camelia e argan.','Eļļa gludumam un mirdzumam ar kamēlijas un argāna eļļu.','Масло для гладкости и блеска с маслами камелии и арганы.')],
[1826,'prima-blond-oil',M('Prima Blond · care oil','Prima Blond · olio trattante','Prima Blond · kopšanas eļļa','Prima Blond · масло-уход'),19,false,M('Care oil for nourishment, smoothness, shine and heat protection.','Olio trattante per nutrimento, morbidezza, lucentezza e protezione dal calore.','Kopšanas eļļa barošanai, gludumam, mirdzumam un termoaizsardzībai.','Масло-уход для питания, гладкости, блеска и термозащиты.')],
[1827,'couture-luxury-blond-oil',M('Couture Luxury Blond · oil','Couture Luxury Blond · olio','Couture Luxury Blond · eļļa','Couture Luxury Blond · масло'),20.4,true,M('Shine and protection with argan and macadamia oils.','Lucentezza e protezione con oli di argan e macadamia.','Mirdzums un aizsardzība ar argāna un makadāmijas eļļām.','Блеск и защита с маслами арганы и макадамии.')],
[1828,'couture-luxury-color-spray',M('Couture Luxury Color · two-phase spray','Couture Luxury Color · spray bifasico','Couture Luxury Color · divfāžu sprejs','Couture Luxury Color · двухфазный спрей'),20.4,true,M('A colour-care spray with silk proteins, keratin and argan oil.','Spray per capelli colorati con proteine della seta, cheratina e olio di argan.','Sprejs krāsotiem matiem ar zīda proteīniem, keratīnu un argāna eļļu.','Спрей для окрашенных волос с протеинами шёлка, кератином и маслом арганы.')],
[1829,'couture-luxury-color-shampoo',M('Couture Luxury Color · shampoo','Couture Luxury Color · shampoo','Couture Luxury Color · šampūns','Couture Luxury Color · шампунь'),19.4,true,M('Sulphate-free shampoo for gentle cleansing and colour care.','Shampoo senza solfati per una detersione delicata dei capelli colorati.','Šampūns bez sulfātiem saudzīgai mazgāšanai un krāsas kopšanai.','Бессульфатный шампунь для мягкого очищения и сохранения цвета.')],
[1830,'couture-luxury-color-balm',M('Couture Luxury Color · conditioner','Couture Luxury Color · balsamo','Couture Luxury Color · balzams','Couture Luxury Color · бальзам'),20.4,true,M('Conditioning care for colour brightness and smoothness.','Balsamo per la brillantezza del colore e la morbidezza.','Balzams krāsas spilgtumam un matu gludumam.','Бальзам для яркости цвета и гладкости волос.')],
[1831,'couture-velvet-spray',M('Couture Velvet 0.3 · detangling spray','Couture Velvet 0.3 · spray districante','Couture Velvet 0.3 · sprejs ķemmēšanai','Couture Velvet 0.3 · спрей для расчёсывания'),14.4,false,M('A spray to make detangling easier. 0.3 is the product reference, not the bottle volume.','Spray per facilitare la pettinatura. 0.3 è il codice prodotto, non il volume.','Sprejs vieglākai ķemmēšanai. 0.3 ir produkta apzīmējums, nevis tilpums.','Спрей для облегчения расчёсывания. 0.3 — обозначение продукта, а не объём.')],
[1834,'otium-aqua-shampoo',M('Otium Aqua · shampoo, 1 L','Otium Aqua · shampoo, 1 L','Otium Aqua · šampūns, 1 l','Otium Aqua · шампунь, 1 л'),29,false,M('Sulphate-free hydration care for dry hair. A one-litre professional format.','Trattamento idratante senza solfati per capelli secchi. Formato professionale da un litro.','Mitrinoša kopšana bez sulfātiem sausiem matiem. Profesionāls viena litra iepakojums.','Увлажняющий уход без сульфатов для сухих волос. Профессиональный формат — один литр.')],
[1835,'otium-aqua-conditioner',M('Otium Aqua · conditioner, 1 L','Otium Aqua · balsamo, 1 L','Otium Aqua · balzams, 1 l','Otium Aqua · бальзам, 1 л'),29,false,M('Moisturising conditioner for dry hair, in a one-litre format.','Balsamo idratante per capelli secchi, nel formato da un litro.','Mitrinošs balzams sausiem matiem viena litra iepakojumā.','Увлажняющий бальзам для сухих волос, объём один литр.')],
[1836,'otium-aqua-mask',M('Otium Aqua · mask, 300 ml','Otium Aqua · maschera, 300 ml','Otium Aqua · maska, 300 ml','Otium Aqua · маска, 300 мл'),27,false,M('A moisturising mask for dry hair. Follow the product instructions for application.','Maschera idratante per capelli secchi. Segui le istruzioni sulla confezione.','Mitrinoša maska sausiem matiem. Lieto saskaņā ar norādījumiem uz iepakojuma.','Увлажняющая маска для сухих волос. Применяйте по инструкции на упаковке.')],
[1837,'couture-luxury-blond-shampoo',M('Couture Luxury Blond · shampoo, 1 L','Couture Luxury Blond · shampoo, 1 L','Couture Luxury Blond · šampūns, 1 l','Couture Luxury Blond · шампунь, 1 л'),40,true,M('Sulphate-free care for blonde hair, with a focus on hydration and shade brightness.','Cura senza solfati per capelli biondi, per idratazione e luminosità del colore.','Kopšana bez sulfātiem blondiem matiem — mitrināšanai un toņa spilgtumam.','Бессульфатный уход для светлых волос: увлажнение и яркость оттенка.')],
[1838,'couture-luxury-blond-conditioner',M('Couture Luxury Blond · conditioner, 1 L','Couture Luxury Blond · balsamo, 1 L','Couture Luxury Blond · balzams, 1 l','Couture Luxury Blond · бальзам, 1 л'),44,true,M('Conditioning care for blonde hair, nourishment and shine.','Balsamo per nutrimento e lucentezza dei capelli biondi.','Balzams blondo matu barošanai un mirdzumam.','Бальзам для питания и блеска светлых волос.')],
[1839,'couture-silk-primer',M('Couture Silk 0.7 · two-phase primer','Couture Silk 0.7 · primer bifasico','Couture Silk 0.7 · divfāžu praimeris','Couture Silk 0.7 · двухфазный праймер'),24.5,true,M('A styling primer with hyaluronic acid, for shine, easier styling and heat protection.','Primer con acido ialuronico per lucentezza, styling più semplice e protezione termica.','Praimeris ar hialuronskābi mirdzumam, vieglākai veidošanai un termoaizsardzībai.','Праймер с гиалуроновой кислотой для блеска, облегчения укладки и термозащиты.')],
[1840,'couture-batiste-heat-protection',M('Couture Batiste 1.3 · heat protection','Couture Batiste 1.3 · termoprotettore','Couture Batiste 1.3 · termoaizsardzība','Couture Batiste 1.3 · термозащита'),18.2,true,M('Heat-protection spray. Follow the label and the care guidance for your hair piece.','Spray termoprotettore. Segui l’etichetta e le indicazioni di cura del tuo prodotto.','Termoaizsardzības sprejs. Ievēro iepakojuma norādes un matu izstrādājuma kopšanas ieteikumus.','Термозащитный спрей. Следуйте инструкции и рекомендациям по уходу за изделием.')]
];
for(const [sourceId,slug,name,price,soldOut,description] of careRows) products.push({id:slug,sourceId,slug,name,category:'hair-care',description,images:[imagePath(sourceId)],shades:[],textures:[],variants:[{id:'standard',label:M('Standard','Standard','Standarta','Стандарт'),price}],material:'care',soldOut,brand:'ESTEL'});
export const categoryWords:Record<Category,Word>={wigs:'wigs',ponytails:'ponytails','clip-ins':'clips',hairpieces:'hairpieces','natural-hair':'natural','hair-care':'care'};
export const categories:Category[]=['wigs','ponytails','clip-ins','hairpieces','natural-hair','hair-care'];
export const categoryImages:Record<Category,string>={wigs:imagePath(1848,1),ponytails:imagePath(1820,2),'clip-ins':imagePath(1960,3),hairpieces:imagePath(1847,4),'natural-hair':imagePath(1822,3),'hair-care':imagePath(1834)};
export const categoryDescriptions:Record<Category,LocalText>={
wigs:M('Natural hair, beautifully personal. Explore our ready-made wigs, or let us create a piece around you.','Capelli naturali, una bellezza personale. Scopri le parrucche pronte o richiedi un modello su misura.','Dabīgie mati ar personīgu raksturu. Apskati gatavās parūkas vai pasūti sev pielāgotu izstrādājumu.','Натуральные волосы и индивидуальный образ. Выберите готовый парик или обсудите изготовление на заказ.'),
ponytails:M('Length, fullness and a new way to wear your hair. Handcrafted from natural Slavic hair.','Lunghezza, volume e un nuovo modo di portare i capelli. Code realizzate a mano con capelli slavi naturali.','Garums, kuplums un jauns tēls. Ar rokām darinātas zirgastes no dabīgiem slāvu matiem.','Длина, объём и новый образ. Хвосты ручной работы из натуральных славянских волос.'),
'clip-ins':M('A little extra, whenever you want it. Removable pieces for effortless length and volume.','Qualcosa in più, quando vuoi. Ciocche rimovibili per aggiungere lunghezza e volume.','Nedaudz vairāk, kad vien vēlies. Noņemamas šķipsnas garumam un apjomam.','Больше длины и объёма, когда захочется. Съёмные пряди для вашего образа.'),
hairpieces:M('Targeted volume, a natural blend. Discover natural-hair pieces for the crown and thinning areas.','Volume dove serve, un effetto naturale. Scopri gli infoltitori per la sommità e le zone diradate.','Apjoms vajadzīgajā vietā, dabisks rezultāts. Matu uzlikas galvas virspusei un retinātām zonām.','Объём там, где он нужен. Накладки из натуральных волос для теменной зоны и участков поредения.'),
'natural-hair':M('Selected Slavic and European hair for professional work. Capsules and cut hair, in a considered palette of shades.','Capelli slavi ed europei selezionati per il lavoro professionale. Ciocche con cheratina e capelli in taglio, in una gamma di tonalità naturali.','Atlasīti slāvu un Eiropas mati profesionālam darbam. Kapsulas un mati griezumā dažādos dabiskos toņos.','Отборные славянские и европейские волосы для профессиональной работы. Капсулы и срезы в широкой палитре оттенков.'),
'hair-care':M('Professional care selected by our team. Explore ESTEL ranges for cleansing, conditioning and styling.','Cura professionale selezionata dal nostro team. Scopri le linee ESTEL per detersione, trattamento e styling.','Mūsu komandas izvēlēta profesionāla kopšana. ESTEL līdzekļi mazgāšanai, kondicionēšanai un veidošanai.','Профессиональный уход, отобранный нашей командой. Средства ESTEL для очищения, кондиционирования и укладки.')};
export const findProduct=(slug:string)=>products.find(p=>p.slug===slug);
export const minPrice=(p:Product)=>Math.min(...p.variants.map(v=>v.price));
export const productImagesForShade=(p:Product,shade:string,texture?:string)=>
 [...new Set([...shadePhotosFor(p.id,shade,texture).map(photo=>photo.src),...p.images])];
export const company={name:'SIA Beauty Mafia ISL',address:'Mihoelsa 47, Daugavpils, Latvia',phone:'+371 28237807',tel:'+37128237807',email:'bmhair.lv@gmail.com',whatsapp:'https://wa.me/37128237807',instagram:'https://www.instagram.com/beauty_mafia_iwoman/',facebook:'https://www.facebook.com/MafiaDaugavpils/'};
