"use client";
import {useEffect,useRef} from 'react';
import {useBM} from './context';
import {products} from '@/lib/bm/catalog';
import {validateLine,resolveLine,type BagLine} from '@/lib/bm/cart';
type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
type Registry={registerTool:(tool:Tool,options?:{signal:AbortSignal})=>void|Promise<void>};
export function AgentTools(){const context=useBM();const latest=useRef(context);latest.current=context;
 useEffect(()=>{const registry=(document as Document&{modelContext?:Registry}).modelContext;if(!registry?.registerTool)return;const lifecycle=new AbortController();
 const snapshot=()=>latest.current.bag.map(l=>{const{product:p,variant:v}=resolveLine(l);return{...l,name:p.name[latest.current.locale],unitPrice:v.price,currency:'EUR'};});
 const tools:Tool[]=[{name:'search_bmhair_catalogue',description:'Read the BM HAIR preview catalogue, prices, published availability and selectable variants. Does not place an order.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:150}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){const x=input as {query?:unknown};if(!x||typeof x!=='object'||(x.query!==undefined&&typeof x.query!=='string'))throw Error('query must be a string');const query=String(x.query||'').toLowerCase();if(query.length>150)throw Error('query is too long');return products.filter(p=>`${p.name.en} ${p.name[latest.current.locale]} ${p.category} ${p.shades.join(' ')}`.toLowerCase().includes(query)).map(p=>({id:p.id,name:p.name[latest.current.locale],url:latest.current.href(`products/${p.slug}`),soldOut:!!p.soldOut,requestOnly:p.id==='wig-dark',shades:p.shades,textures:p.textures,variants:p.variants.map(v=>({id:v.id,label:v.label[latest.current.locale],price:v.price})),currency:'EUR',liveInventory:false}));}},{name:'read_bmhair_bag',description:'Read the device-local preview bag. Does not submit an order or contact BM HAIR.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return{lines:snapshot(),paymentEnabled:false};}},{name:'stage_bmhair_bag_items',description:'Add validated catalogue selections to the visible device-local bag and open it for review. No order, payment, upload or enquiry is submitted.',inputSchema:{type:'object',properties:{items:{type:'array',minItems:1,maxItems:20,items:{type:'object',properties:{productId:{type:'string'},variantId:{type:'string'},shade:{type:'string'},texture:{type:'string'},quantity:{type:'integer',minimum:1,maximum:300}},required:['productId','variantId','shade','texture','quantity'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const x=input as {items?:unknown[]};if(!Array.isArray(x?.items)||!x.items.length||x.items.length>20)throw Error('Supply 1–20 items');const lines=x.items.map(validateLine);if(lines.some(l=>!l))throw Error('Invalid, unavailable or request-only selection');lines.forEach(l=>latest.current.add(l as BagLine));await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return{status:'staged_for_review',lines:snapshot(),orderPlaced:false};}}];
 tools.forEach(tool=>{try{Promise.resolve(registry.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}});return()=>lifecycle.abort();
 },[]);return null;
}
