"use client";
import {useMemo,useState} from 'react';
import {Search,ArrowUpRight,MessageCircle,Truck,ShieldCheck,ZoomIn,X} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {useBM,asset} from './context';
import {shadePhotosFor} from '@/lib/bm/shade-photos';
import {Photo,ProductCard,Breadcrumb,PageHeading,SelectField,Quantity,InfoAccordion,HelpBlock,Action,TextLink,Empty,enquiryPrice} from './common';
import {categories,categoryWords,categoryDescriptions,categoryImages,products,shades,minPrice,productImagesForShade,type Product,type Category} from '@/lib/bm/catalog';
import {M,money} from '@/lib/bm/i18n';
import {productIsRequestOnly} from '@/lib/bm/cart';

export function Collection({category}:{category?:Category}){const{locale,t,href}=useBM();const[query,setQuery]=useState('');const[shade,setShade]=useState('all');const[texture,setTexture]=useState('all');const[sort,setSort]=useState('featured');const list=useMemo(()=>products.filter(p=>(!category||p.category===category)&&`${p.name[locale]} ${p.name.en} ${p.shades.join(' ')}`.toLowerCase().includes(query.toLowerCase())&&(shade==='all'||p.shades.some(s=>shades[s]?.group===shade))&&(texture==='all'||p.textures.includes(texture as 'straight'|'wavy'))).sort((a,b)=>sort==='low'?minPrice(a)-minPrice(b):sort==='high'?minPrice(b)-minPrice(a):Number(!!a.soldOut)-Number(!!b.soldOut)),[category,locale,query,shade,texture,sort]);const clear=()=>{setQuery('');setShade('all');setTexture('all');};
 return <div className="collection-page"><div className="page-container"><Breadcrumb items={[{label:t('shop'),to:category?'shop':undefined},...(category?[{label:t(categoryWords[category])}]:[])]}/><PageHeading eyebrow="BM HAIR COLLECTION" title={category?t(categoryWords[category]):t('all')} text={category?categoryDescriptions[category][locale]:M('Find your hair. Find your own kind of beautiful.','Trova i tuoi capelli. Esprimi la tua bellezza.','Atrodi savus matus. Izcel savu skaistumu.','Найдите свои волосы. Подчеркните свою красоту.')[locale]}/><nav className="category-tabs" aria-label={t('shop')}><a className={!category?'active':''} href={href('shop')}>{t('all')}</a>{categories.map(c=><a className={category===c?'active':''} href={href(`collections/${c}`)} key={c}>{t(categoryWords[c])}</a>)}</nav>
 {category==='hairpieces'?<div className="hairpieces-discovery"><div className="hairpiece-type"><span className="eyebrow">BM HAIR ATELIER</span><h2>{t('hairpieces')}</h2><p>{M('A natural-hair piece can add volume where you want it most. Our published range includes clip attachment and silk scalp-effect bases on selected pieces. Ask us about the construction, dimensions, shade and price of the exact piece.','Un infoltitore in capelli naturali aggiunge volume dove desideri. La gamma comprende fissaggio a clip e basi in seta effetto cute su alcuni modelli. Chiedici costruzione, dimensioni, tonalità e prezzo del prodotto preciso.','Dabīgo matu uzlika piešķir apjomu vēlamajā vietā. Atsevišķiem modeļiem ir sprādzes un zīda pamatne ar ādas efektu. Jautā par konkrētā izstrādājuma konstrukciju, izmēriem, toni un cenu.','Накладка из натуральных волос добавляет объём в нужной зоне. Для отдельных моделей предусмотрены клипсы и шёлковая основа с имитацией кожи. Уточните конструкцию, размеры, оттенок и цену конкретного изделия.')[locale]}</p><Action to="contact">{t('help')}</Action><TextLink to="guide/wigs-or-hair-pieces">{t('readGuide')}</TextLink></div><div className="hairpiece-links"><p className="eyebrow">{t('needHelpText')}</p><h2>{M('Let’s find your fit.','Troviamo la soluzione per te.','Atradīsim piemērotāko.','Найдём ваш вариант.')[locale]}</h2><a href={href('collections/wigs')}>{t('wigs')}<ArrowUpRight/></a><a href={href('collections/clip-ins')}>{t('clips')}<ArrowUpRight/></a><a href={href('custom')}>{t('custom')}<ArrowUpRight/></a></div></div>:<><div className="filter-bar"><div className="catalog-search"><Search size={18}/><input aria-label={t('search')} placeholder={t('search')} value={query} onChange={e=>setQuery(e.target.value)}/></div>{category!=='hair-care'&&<><SelectField id="shade-filter" label={t('shade')} value={shade} onChange={setShade} options={['all','blonde','brunette','ombre'].map(s=>({value:s,label:t(s==='all'?'allShades':s as 'blonde'|'brunette'|'ombre')}))}/><SelectField id="texture-filter" label={t('texture')} value={texture} onChange={setTexture} options={['all','straight','wavy'].map(s=>({value:s,label:t(s==='all'?'allTextures':s as 'straight'|'wavy')}))}/></>}<SelectField id="sort" label={t('sort')} value={sort} onChange={setSort} options={[{value:'featured',label:t('featured')},{value:'low',label:t('lowHigh')},{value:'high',label:t('highLow')}]}/></div><div className="results-info"><span aria-live="polite">{list.length} {t('items')}</span>{(query||shade!=='all'||texture!=='all')&&<button onClick={clear}>{t('clear')}<X size={14}/></button>}</div>{list.length?<div className="product-grid">{list.map((p,i)=><ProductCard product={p} key={p.id} index={i}/>)}</div>:<Empty title={t('noResults')}><button className="button button-outline" onClick={clear}>{t('clear')}</button></Empty>}</>}
 <HelpBlock/></div></div>;}

export function ProductPage({product:p}:{product:Product}){const{locale,t,href,add}=useBM();const[variantId,setVariantId]=useState(p.variants[0].id);const[shade,setShade]=useState(p.shades[0]||'');const[texture,setTexture]=useState<string>(p.textures[0]||'');const[quantity,setQuantity]=useState(1);const[index,setIndex]=useState(0);const[zoom,setZoom]=useState(false);const variant=p.variants.find(v=>v.id===variantId)!;const images=productImagesForShade(p,shade,texture);const selected=images[index]||images[0];const material=p.material==='care'?'ESTEL':p.material==='slavic'?t('slavicHair'):p.material==='european'?M('Natural European hair','Capelli europei naturali','Dabīgie Eiropas mati','Натуральные европейские волосы')[locale]:t('naturalHair');const requestOnly=productIsRequestOnly(p);
 const references=shadePhotosFor(p.id,shade,texture);
 const referenceCaption=M('Original BM HAIR shade reference','Foto originale BM HAIR della tonalità','Oriģinālais BM HAIR toņa attēls','Оригинальное фото оттенка BM HAIR')[locale];
 const referenceNote=M('Shade reference only. Length, texture and construction may differ.','Riferimento del colore. Lunghezza, texture e struttura possono variare.','Toņa paraugs. Garums, struktūra un konstrukcija var atšķirties.','Пример оттенка. Длина, структура и конструкция могут отличаться.')[locale];
 const isReference=(src:string)=>references.some(photo=>photo.src===src);
 const imageCaption=(src:string)=>isReference(src)?`${referenceCaption} · ${shade}. ${referenceNote}`:t('collectionPhoto');
 const careText=M('Follow the instructions supplied with your piece. Use gentle care and avoid excessive heat. Before colouring or changing the construction, speak to our team about suitability and guarantee conditions.','Segui le istruzioni del prodotto. Usa un trattamento delicato ed evita il calore eccessivo. Prima di colorare o modificare la struttura, chiedi al team informazioni e condizioni di garanzia.','Ievēro izstrādājumam pievienotās norādes. Kop saudzīgi un izvairies no pārmērīga karstuma. Pirms krāsošanas vai konstrukcijas izmaiņām sazinies par piemērotību un garantijas noteikumiem.','Следуйте инструкции к изделию. Ухаживайте бережно, избегайте перегрева. Перед окрашиванием или изменением конструкции уточните допустимые процедуры и условия гарантии.')[locale];
 return <><div className="page-container"><Breadcrumb items={[{label:t('shop'),to:'shop'},{label:t(categoryWords[p.category]),to:`collections/${p.category}`},{label:p.name[locale]}]}/><div className="product-detail"><div className="product-gallery"><button className={`main-product-image${isReference(selected)?' shade-reference-image':''}`} onClick={()=>setZoom(true)} aria-label={`${t('details')}: ${p.name[locale]}`}><Photo src={selected} alt={`${p.name[locale]} — ${imageCaption(selected)}`} priority fit="contain"/><span className="zoom-control"><ZoomIn size={20}/></span></button>{images.length>1&&<div className="gallery-thumbnails">{images.map((src,i)=><button key={`${src}-${i}`} onClick={()=>setIndex(i)} aria-label={`${p.name[locale]} ${i+1}`} aria-pressed={i===index}><Photo src={src} alt={`${p.name[locale]} ${i+1}`} fit="contain"/></button>)}</div>}<p className="fine-print" aria-live="polite">{imageCaption(selected)}</p></div><div className="product-config"><p className="eyebrow">{p.brand} / {t(categoryWords[p.category])}</p><h1>{p.name[locale]}</h1><p className="pdp-price" aria-live="polite">{requestOnly?enquiryPrice[locale]:<>{money(variant.price,locale)}{p.unit&&<small>{t(p.unit==='capsule'?'perCapsule':'per100')}</small>}</>}</p><p className="pdp-description">{p.description[locale]}</p>
 {p.shades.length>0&&<fieldset className="option-group"><legend>{t('shade')} <span>{shades[shade]?.name[locale]||shade} · {shade}</span></legend><RadioGroup value={shade} onValueChange={s=>{setShade(s);setIndex(0);}} className="shade-options" aria-label={t('shade')}>{p.shades.map(s=><label key={s} title={`${s} ${shades[s]?.name[locale]||''}`} className={`shade-choice${shade===s?' chosen':''}`}><RadioGroupItem value={s} aria-label={`${s} ${shades[s]?.name[locale]||''}`} className={`shade-radio${shadePhotosFor(p.id,s)[0]?' shade-photo':''}`} style={{background:shadePhotosFor(p.id,s)[0]?`#fff url("${asset(shadePhotosFor(p.id,s)[0].src)}") center / contain no-repeat`:shades[s]?.hex||'#654f3e'}}/><span>{s}</span></label>)}</RadioGroup><p className="fine-print">{t('colourNote')} <a href={href('guide/choosing-your-shade')}>{t('readGuide')}</a></p></fieldset>}
 <SelectField id="product-variant" label={p.variants.some(v=>v.length)?t('length'):t('size')} value={variantId} onChange={setVariantId} options={p.variants.map(v=>({value:v.id,label:v.label[locale]}))}/>
 {p.textures.length>0&&<fieldset className="option-group"><legend>{t('texture')}</legend><RadioGroup value={texture} onValueChange={value=>{setTexture(value);setIndex(0);}} className="texture-options" aria-label={t('texture')}>{p.textures.map(s=><label key={s} className={texture===s?'chosen':''}><RadioGroupItem value={s}/><span>{t(s)}</span></label>)}</RadioGroup></fieldset>}
 {requestOnly?<div className="request-purchase"><p>{M('This collection includes several styles. Our team will confirm the exact wig and availability before you order.','La collezione comprende diversi stili. Il team confermerà il modello preciso e la disponibilità prima dell’ordine.','Kolekcijā ir vairāki stili. Pirms pasūtījuma komanda precizēs konkrēto parūku un pieejamību.','В коллекции несколько моделей. Перед заказом команда подтвердит конкретный парик и наличие.')[locale]}</p><Action to="contact">{t('help')}</Action></div>:<div className="purchase-row"><Quantity value={quantity} onChange={setQuantity}/><button className="button" disabled={p.soldOut} onClick={()=>add({productId:p.id,variantId,shade,texture,quantity})}>{p.soldOut?t('soldout'):t('add')}<ArrowUpRight size={18}/></button></div>}
 {!requestOnly&&!p.soldOut&&<p className="selection-total" aria-live="polite"><span>{M('Selected quantity','Quantità selezionata','Izvēlētais daudzums','Выбранное количество')[locale]}: {quantity} × {money(variant.price,locale)}</span><strong>{money(variant.price*quantity,locale)}</strong></p>}
 <div className="product-assurances"><a href={href('shipping')}><Truck size={18}/>{t('euroDelivery')}</a><a href={href('guarantee')}><ShieldCheck size={18}/>{t('guarantee')}</a></div>
 <InfoAccordion items={[{title:t('productInfo'),body:<><dl className="specifications"><div><dt>{t('productType')}</dt><dd>{t(categoryWords[p.category])}</dd></div><div><dt>{t('details')}</dt><dd>{material}</dd></div>{variant.grams&&<div><dt>{t('density')}</dt><dd>{variant.grams} g</dd></div>}{variant.length&&<div><dt>{t('length')}</dt><dd>{variant.label[locale]}</dd></div>}</dl>{p.id==='capsules'&&<CapsuleQuantityGuide/>}</>},{title:t('howCare'),body:<><p>{p.material==='care'?M('Follow the manufacturer’s directions on the product packaging. Ask us if you need help selecting care for your hair piece.','Segui le istruzioni del produttore sulla confezione. Chiedici aiuto per scegliere i prodotti adatti.','Ievēro ražotāja norādes uz iepakojuma. Jautā, ja vajadzīga palīdzība kopšanas izvēlē.','Следуйте указаниям производителя на упаковке. Мы поможем подобрать уход к вашему изделию.')[locale]:careText}</p><TextLink to="guide/caring-for-natural-hair">{t('readGuide')}</TextLink></>},{title:t('shipping'),body:<><p>{t('lvDelivery')}</p><p>{t('euDelivery')}</p><TextLink to="shipping">{t('details')}</TextLink></>},{title:t('returns'),body:<><p>{M('If something is not right, contact our team with your order details and photographs. The quality promise is separate from your statutory rights. Read the full guarantee and returns information before ordering.','Se qualcosa non va, contattaci con i dati dell’ordine e le foto. La promessa di qualità è distinta dai tuoi diritti di legge. Leggi tutte le informazioni prima di ordinare.','Ja kaut kas nav kārtībā, sazinies, norādot pasūtījumu un pievienojot foto. Kvalitātes solījums ir atsevišķs no likumā noteiktajām tiesībām. Pirms pirkuma izlasi pilno informāciju.','Если что-то не так, напишите нам с данными заказа и фото. Обещание качества дополняет ваши законные права. Ознакомьтесь с полными условиями до покупки.')[locale]}</p><TextLink to="returns">{t('readTerms')}</TextLink></>}]}/><HelpBlock/></div></div>
 <section className="related-section"><div className="section-heading"><h2>{t(p.material==='care'?'complete':'related')}</h2><TextLink to={`collections/${p.category}`}>{t('viewAll')}</TextLink></div><div className="product-grid">{products.filter(x=>x.id!==p.id&&(x.category===p.category||x.id==='otium-aqua-mask')).slice(0,4).map(x=><ProductCard product={x} key={x.id}/>)}</div></section></div>
 <Dialog open={zoom} onOpenChange={setZoom}><DialogContent className="gallery-dialog" showCloseButton={false}><DialogTitle className="sr-only">{p.name[locale]}</DialogTitle><DialogDescription className="sr-only">{imageCaption(selected)}</DialogDescription><DialogClose className="icon-button gallery-close" aria-label={t('close')}><X/></DialogClose><Photo src={selected} alt={`${p.name[locale]} — ${imageCaption(selected)}`} fit="contain"/>{images.length>1&&<div className="gallery-controls">{images.map((_,i)=><button key={i} aria-label={`${p.name[locale]} ${i+1}`} aria-pressed={i===index} onClick={()=>setIndex(i)}>{i+1}</button>)}</div>}</DialogContent></Dialog></>;
}

function CapsuleQuantityGuide(){
 const{locale,t}=useBM();
 return <div className="capsule-guide"><h3>{M('How many capsules?','Quante ciocche?','Cik kapsulu nepieciešams?','Сколько нужно капсул?')[locale]}</h3>
 <p>{M('BM HAIR’s guide for average density. These are approximate ranges; your stylist should confirm the amount for your own hair, texture and desired result.','La guida BM HAIR per una densità media. Sono quantità indicative: il tuo stylist deve confermarle in base ai tuoi capelli, alla texture e al risultato desiderato.','BM HAIR ieteikumi vidējam biezumam. Daudzumi ir aptuveni; meistars tos precizēs atbilstoši taviem matiem, struktūrai un vēlamajam rezultātam.','Ориентир BM HAIR для средней густоты. Количество приблизительное: мастер уточнит его с учётом ваших волос, структуры и желаемого результата.')[locale]}</p>
 <table><caption className="sr-only">{M('Approximate capsule quantities by length','Quantità indicative per lunghezza','Aptuvenais kapsulu skaits pēc garuma','Примерное количество капсул по длине')[locale]}</caption><thead><tr><th scope="col">{t('length')}</th><th scope="col">{t('quantity')}</th></tr></thead><tbody>{[['50 cm','140–160'],['60 cm','160–200'],['70 cm','200–260']].map(([length,amount])=><tr key={length}><th scope="row">{length}</th><td>{amount}</td></tr>)}</tbody></table>
 <p>{M('For 40 cm or a personalised amount, ask your stylist. One unit in your bag is one capsule.','Per 40 cm o una quantità personalizzata, chiedi al tuo stylist. Un’unità nella bag corrisponde a una ciocca con cheratina.','Par 40 cm vai individuālu daudzumu jautā meistaram. Viena vienība grozā ir viena kapsula.','Для длины 40 см или индивидуального расчёта обратитесь к мастеру. Одна единица в корзине — одна капсула.')[locale]}</p></div>;
}
