"use client";
import {useId} from 'react';
import {productIsRequestOnly} from '@/lib/bm/cart';
import {ArrowUpRight,ArrowRight,Minus,Plus,Check,Truck,MessageCircle,ShieldCheck} from 'lucide-react';
import {useBM,asset} from './context';
import {money,type LocalText,M} from '@/lib/bm/i18n';
import {type Product,categoryWords,minPrice,shades} from '@/lib/bm/catalog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
export function Photo({src,alt,className='',priority=false,fit='cover'}:{src:string;alt:string;className?:string;priority?:boolean;fit?:'cover'|'contain'}){return <img src={asset(src)} alt={alt} className={className} width={1000} height={1300} style={{objectFit:fit}} loading={priority?'eager':'lazy'} decoding="async" fetchPriority={priority?'high':undefined}/>;}
export function Action({to,children,secondary=false,light=false}:{to:string;children:React.ReactNode;secondary?:boolean;light?:boolean}){const{href}=useBM();return <a className={`button ${secondary?'button-outline':''} ${light?'button-light':''}`} href={href(to)}>{children}<ArrowUpRight size={17} strokeWidth={1.5}/></a>;}
export function TextLink({to,children}:{to:string;children:React.ReactNode}){const{href}=useBM();return <a className="text-link" href={href(to)}>{children}<ArrowUpRight size={16}/></a>;}
export function SelectField({label,value,onChange,options,id,className=''}:{label:string;value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];id?:string;className?:string}){return <div className={`select-field ${className}`}><label id={id?`${id}-label`:undefined} htmlFor={id}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger id={id} aria-label={label} className="bm-select"><SelectValue>{options.find(o=>o.value===value)?.label}</SelectValue></SelectTrigger><SelectContent position="popper" className="bm-select-menu">{options.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></div>;}
export function Quantity({value,onChange,id}:{value:number;onChange:(n:number)=>void;id?:string}){const{t}=useBM();const generatedId=useId();return <div className="quantity"><button type="button" aria-label={`${t('remove')} 1`} disabled={value<=1} onClick={()=>onChange(value-1)}><Minus size={14}/></button><input id={id||generatedId} type="number" step={1} inputMode="numeric" min={1} max={300} aria-label={t('quantity')} value={value} onChange={e=>onChange(Math.max(1,Math.min(300,Math.floor(Number(e.target.value))||1)))}/><button type="button" aria-label={`${t('add')} 1`} disabled={value>=300} onClick={()=>onChange(value+1)}><Plus size={14}/></button></div>;}
export function ProductCard({product:p,index=0}:{product:Product;index?:number}){const{locale,t,href}=useBM();return <article className="product-card"><a href={href(`products/${p.slug}`)} className="product-image"><Photo src={p.images[0]} alt={p.name[locale]} priority={index<2}/>{productIsRequestOnly(p)?<span className="product-tag">{enquiryPrice[locale]}</span>:p.soldOut?<span className="product-tag">{t('soldout')}</span>:p.brand==='ESTEL'?<span className="product-tag subtle">ESTEL</span>:null}<span className="product-open" aria-hidden="true"><ArrowUpRight size={20}/></span></a><div className="product-card-top"><span className="meta">{t(categoryWords[p.category])}</span>{p.shades.length>0&&<div className="mini-swatches" aria-label={`${p.shades.length} ${t('shade')}`}>{p.shades.slice(0,4).map(s=><span key={s} style={{background:shades[s]?.hex||'#56433c'}}/>)}{p.shades.length>4&&<small>+{p.shades.length-4}</small>}</div>}</div><h3><a href={href(`products/${p.slug}`)}>{p.name[locale]}</a></h3><p className="product-price">{productIsRequestOnly(p)?enquiryPrice[locale]:<>{p.variants.length>1&&<span>{t('from')} </span>}{money(minPrice(p),locale)}{p.unit&&<span className="unit"> · {t(p.unit==='capsule'?'perCapsule':'per100')}</span>}</>}</p></article>;}
export function Breadcrumb({items}:{items:{label:string;to?:string}[]}){const{href,t}=useBM();return <nav className="breadcrumb" aria-label="Breadcrumb"><a href={href()}>{t('home')}</a>{items.map((x,i)=><span key={i}><span aria-hidden="true">/</span>{x.to?<a href={href(x.to)}>{x.label}</a>:<span aria-current="page">{x.label}</span>}</span>)}</nav>;}
export function PageHeading({eyebrow,title,text}:{eyebrow?:string;title:string;text?:string}){return <div className="page-heading">{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{text&&<p className="lead">{text}</p>}</div>;}
export function InfoAccordion({items}:{items:{title:string;body:React.ReactNode}[]}){return <Accordion type="multiple" className="bm-accordion">{items.map((x,i)=><AccordionItem value={String(i)} key={i}><AccordionTrigger>{x.title}</AccordionTrigger><AccordionContent>{x.body}</AccordionContent></AccordionItem>)}</Accordion>;}
export function TrustStrip(){const{t}=useBM();return <div className="trust-strip"><span><Check size={17}/>{t('naturalHair')}</span><span><ShieldCheck size={17}/>{t('professional')}</span><span><Truck size={18}/>{t('euroDelivery')}</span></div>;}
export function HelpBlock(){const{t}=useBM();return <div className="help-block"><MessageCircle size={21}/><div><h3>{t('help')}</h3><p>{t('needHelpText')}</p><TextLink to="contact">{t('contact')}</TextLink></div></div>;}
export function Empty({title,text,children}:{title:string;text?:string;children?:React.ReactNode}){return <div className="empty-state"><h2>{title}</h2>{text&&<p>{text}</p>}{children}</div>;}
export const localized=(l:string,text:LocalText)=>text[l as keyof LocalText];
export const previewNotice=M('A design preview. Payments are not active.','Anteprima del sito. I pagamenti non sono attivi.','Dizaina priekšskatījums. Maksājumi nav aktivizēti.','Предварительный просмотр. Оплата пока не подключена.');

export const enquiryPrice=M('Price on enquiry','Prezzo su richiesta','Cena pēc pieprasījuma','Цена по запросу');
