"use client";
import {ArrowUpRight,ArrowDown} from 'lucide-react';
import {useBM} from './context';
import {Photo,Action,TextLink,TrustStrip,ProductCard} from './common';
import {homeCopy as copy,articles,reviews} from '@/lib/bm/content';
import {products,categoryWords} from '@/lib/bm/catalog';

export function Home(){const{locale,t,href}=useBM();const selected=['wig-blonde','ponytail','mono','slavic-cut'].map(id=>products.find(p=>p.id===id)!);return <>
 <section className="hero"><div className="hero-content"><p className="eyebrow">{copy.eyebrow[locale]}</p><h1>{copy.title[locale]}<em>{copy.italic[locale]}</em></h1><p className="hero-intro">{copy.intro[locale]}</p><div className="hero-actions"><Action to="shop">{t('explore')}</Action><TextLink to="quality">{t('quality')}</TextLink></div><p className="hero-origin">{copy.heroNote[locale]}</p></div><div className="hero-image"><Photo src="/images/cat-1847-01.webp" alt={locale==='ru'?'Длинные тёмные волосы — образ BM HAIR':locale==='it'?'Capelli lunghi e scuri — un look BM HAIR':locale==='lv'?'Gari tumši mati — BM HAIR tēls':'Long, flowing dark hair — a BM HAIR editorial look'} priority/><span className="hero-image-caption">01 / THE ART OF NATURAL HAIR</span><a className="hero-scroll" href="#collections" aria-label={t('collectionPhoto')}><ArrowDown size={22}/></a></div></section>
 <TrustStrip/>
 <section id="collections" className="section collections-section"><div className="section-heading"><div><p className="eyebrow">{copy.collectionsLabel[locale]}</p><h2>{copy.collectionsTitle[locale]}</h2></div><TextLink to="shop">{t('viewAll')}</TextLink></div><div className="editorial-collections">{[{category:'wigs' as const,image:'/images/cat-1848-01.webp',n:'01'},{category:'ponytails' as const,image:'/images/cat-1820-01.webp',n:'02'},{category:'clip-ins' as const,image:'/images/cat-1960-01.webp',n:'03'}].map(c=><a key={c.category} className="collection-editorial" href={href(`collections/${c.category}`)}><div className="collection-photo"><Photo src={c.image} alt={`${t(categoryWords[c.category])} — BM HAIR`}/><span className="collection-no">{c.n}</span></div><div className="collection-label"><h3>{t(categoryWords[c.category])}</h3><ArrowUpRight size={25} strokeWidth={1}/></div></a>)}</div></section>
 <section className="section featured-section"><div className="section-heading"><div><p className="eyebrow">{copy.selectionLabel[locale]}</p><h2>{copy.selectionTitle[locale]}</h2></div><TextLink to="shop">{t('shop')}</TextLink></div><div className="product-grid">{selected.map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div></section>
 <section className="quality-story"><div className="quality-photo"><Photo src="/images/craftsmanship.webp" alt={locale==='en'?'Natural hair and professional craftsmanship at BM HAIR':t('professional')}/></div><div className="quality-copy"><p className="eyebrow">{copy.qualityLabel[locale]}</p><h2>{copy.qualityTitle[locale]}</h2><p>{copy.qualityText[locale]}</p><TextLink to="quality">{t('quality')}</TextLink><div className="quality-signature">BM <i>Hair</i></div></div></section>
 <section className="section reviews-section"><div className="section-heading"><div><p className="eyebrow">{t('results')}</p><h2>{locale==='en'?'The difference you feel.':locale==='it'?'La differenza che senti.':locale==='lv'?'Atšķirība, ko jūti.':'Разница, которую чувствуете.'}</h2></div><TextLink to="reviews">{t('viewAll')}</TextLink></div><div className="review-grid">{reviews.slice(0,3).map(r=><article className="review-card" key={r.name}><span className="quote-mark" aria-hidden="true">“</span><p>{r.text[locale]}</p><div><strong>{r.name}</strong><span>{r.product[locale]}</span></div></article>)}</div><p className="fine-print">{t('sourceReviews')}</p></section>
 <section className="custom-band"><div><p className="eyebrow">BM HAIR ATELIER</p><h2>{copy.customTitle[locale]}</h2><p>{copy.customText[locale]}</p><Action to="custom" light>{t('requestCustom')}</Action></div><Photo src="/images/long-blonde.webp" alt={t('custom')} /></section>
 <section className="section journal-section"><div className="section-heading"><div><p className="eyebrow">{t('guide')}</p><h2>{copy.guideTitle[locale]}</h2></div><TextLink to="guide">{t('readGuide')}</TextLink></div><div className="journal-grid">{articles.slice(0,3).map((a,i)=><a className="journal-card" key={a.slug} href={href(`guide/${a.slug}`)}><div className="journal-photo"><Photo src={a.image} alt={a.title[locale]}/><span>0{i+1}</span></div><div className="journal-info"><p className="meta">{t('guide')} · {a.minutes} {t('minutes')}</p><h3>{a.title[locale]}</h3><ArrowUpRight size={22}/></div></a>)}</div></section>
 <section className="professional-band"><div><p className="eyebrow">{t('pro')}</p><h2>{copy.proTitle[locale]}</h2><p>{copy.proText[locale]}</p></div><Action to="professionals" secondary>{t('partnerCta')}</Action></section>
 </>;}
