"use client";
import {useState} from 'react';
import {Search,ShoppingBag,Menu,X,UserRound,ArrowUpRight,Camera,ChevronDown} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetTrigger,SheetClose} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {useBM,navigate} from './context';
import {company,products,categories,categoryWords} from '@/lib/bm/catalog';
import {languageNames,locales,money} from '@/lib/bm/i18n';
import {Photo,TextLink} from './common';
import {BagContents} from './commerce';

export function Header(){const{locale,t,href,path,bag,bagOpen,setBagOpen}=useBM();const[menu,setMenu]=useState(false);const[search,setSearch]=useState(false);const[query,setQuery]=useState('');const matches=products.filter(p=>`${p.name[locale]} ${p.name.en} ${p.description[locale]} ${p.shades.join(' ')}`.toLocaleLowerCase().includes(query.toLocaleLowerCase().trim()));
 const nav=[['shop',t('shop')],['collections/wigs',t('wigs')],['collections/ponytails',t('ponytails')],['collections/clip-ins',t('clips')],['custom',t('custom')],['guide',t('guide')]];
 return <><a className="skip-link" href="#main">{locale==='en'?'Skip to content':locale==='it'?'Vai al contenuto':locale==='lv'?'Pāriet uz saturu':'Перейти к содержимому'}</a><div className="announcement"><span>{t('naturalHair')} <span aria-hidden="true">·</span> {t('euroDelivery')}</span><a href={href('professionals')}>{t('pro')}<ArrowUpRight size={13}/></a></div><header className="site-header"><div className="header-main"><Sheet open={menu} onOpenChange={setMenu}><SheetTrigger asChild><button className="icon-button mobile-menu" aria-label={t('menu')}><Menu size={22}/></button></SheetTrigger><SheetContent side="left" className="menu-sheet" showCloseButton={false}><div className="drawer-head"><SheetTitle>BM HAIR</SheetTitle><SheetClose className="icon-button" aria-label={t('close')}><X/></SheetClose></div><SheetDescription className="sr-only">{t('menu')}</SheetDescription><nav className="mobile-navigation">{nav.map(([to,label])=><a key={to} href={href(to)} onClick={()=>setMenu(false)}>{label}<ArrowUpRight size={20}/></a>)}</nav><div className="mobile-extra">{['quality','about','professionals','contact'].map(p=><a key={p} href={href(p)}>{t(p==='professionals'?'pro':p as 'quality'|'about'|'contact')}</a>)}</div><div className="language-links">{locales.map(l=><a key={l} lang={l} href={`/${l}/${path}`} aria-current={locale===l?'true':undefined}>{languageNames[l]}</a>)}</div></SheetContent></Sheet><a href={href()} className="wordmark" aria-label="BM HAIR Home">BM <span>HAIR</span><small>NATURAL HAIR ATELIER</small></a><nav className="desktop-nav" aria-label={t('menu')}>{nav.map(([to,label])=><a key={to} href={href(to)} aria-current={path===to?'page':undefined}>{label}</a>)}</nav><div className="header-actions"><Select value={locale} onValueChange={l=>navigate(`/${l}/${path}`)}><SelectTrigger className="language-select" aria-label={t('language')}><SelectValue>{locale.toUpperCase()}</SelectValue></SelectTrigger><SelectContent>{locales.map(l=><SelectItem key={l} value={l}>{languageNames[l]}</SelectItem>)}</SelectContent></Select><button className="icon-button" aria-label={t('search')} onClick={()=>setSearch(true)}><Search size={21} strokeWidth={1.5}/></button><a className="icon-button account-icon" aria-label={t('account')} href={href('account')}><UserRound size={20} strokeWidth={1.5}/></a><button className="icon-button bag-button" aria-label={`${t('bag')} (${bag.reduce((s,x)=>s+x.quantity,0)})`} onClick={()=>setBagOpen(true)}><ShoppingBag size={21} strokeWidth={1.5}/>{bag.length>0&&<span className="bag-count">{bag.reduce((s,x)=>s+x.quantity,0)}</span>}</button></div></div></header>
 <Sheet open={bagOpen} onOpenChange={setBagOpen}><SheetContent className="bag-sheet" showCloseButton={false}><div className="drawer-head"><SheetTitle>{t('bag')}</SheetTitle><SheetClose className="icon-button" aria-label={t('close')}><X/></SheetClose></div><SheetDescription className="sr-only">{t('orderReview')}</SheetDescription><BagContents drawer/></SheetContent></Sheet>
 <Dialog open={search} onOpenChange={setSearch}><DialogContent className="search-dialog" showCloseButton={false}><div className="drawer-head"><DialogTitle>{t('search')}</DialogTitle><DialogClose className="icon-button" aria-label={t('close')}><X/></DialogClose></div><DialogDescription className="sr-only">{t('searchHint')}</DialogDescription><div className="search-input"><Search size={20}/><input autoFocus aria-label={t('search')} placeholder={t('searchHint')} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label={t('clear')} onClick={()=>setQuery('')}><X size={18}/></button>}</div><div className="search-results">{matches.length?matches.slice(0,8).map(p=><a key={p.id} href={href(`products/${p.slug}`)} onClick={()=>setSearch(false)}><Photo src={p.images[0]} alt={p.name[locale]}/><span>{p.name[locale]}<small>{t(categoryWords[p.category])}</small></span><span>{t('from')} {money(Math.min(...p.variants.map(v=>v.price)),locale)}</span></a>):<p>{t('noResults')}</p>}</div></DialogContent></Dialog></>;
}

export function Footer(){const{locale,t,href}=useBM();const columns=[{title:t('shopFooter'),items:categories.map(c=>({to:`collections/${c}`,label:t(categoryWords[c])}))},{title:t('discoverFooter'),items:[{to:'quality',label:t('quality')},{to:'custom',label:t('custom')},{to:'about',label:t('about')},{to:'professionals',label:t('pro')},{to:'guide',label:t('guide')},{to:'reviews',label:t('results')}]},{title:t('customerCare'),items:[{to:'contact',label:t('contact')},{to:'shipping',label:t('shipping')},{to:'guarantee',label:t('guarantee')},{to:'returns',label:t('returns')},{to:'account',label:t('account')},{to:'cart',label:t('bag')}]}];return <footer className="site-footer"><div className="footer-main"><div className="footer-brand"><a className="wordmark" href={href()}>BM <span>HAIR</span></a><p>{t('footerIntro')}</p><a href={`mailto:${company.email}`}>{company.email}</a><a href={`tel:${company.tel}`}>{company.phone}</a><a className="social-link" href={company.instagram} target="_blank" rel="noopener noreferrer"><Camera size={19}/> Instagram<ArrowUpRight size={14}/></a></div>{columns.map(c=><div className="footer-column" key={c.title}><h2>{c.title}</h2>{c.items.map(x=><a key={x.to} href={href(x.to)}>{x.label}</a>)}</div>)}</div><div className="footer-bottom"><p>© {new Date().getFullYear()} BM HAIR <span>·</span> {company.name}</p><div><a href={href('privacy')}>{t('privacy')}</a><a href={href('terms')}>{t('terms')}</a><span>EUR €</span><span>{languageNames[locale]}</span></div></div></footer>;}
